// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// puny_encode_cpp
Rcpp::CharacterVector puny_encode_cpp(Rcpp::CharacterVector domains, bool strict);
RcppExport SEXP _punycoder_puny_encode_cpp(SEXP domainsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type domains(domainsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(puny_encode_cpp(domains, strict));
    return rcpp_result_gen;
END_RCPP
}
// puny_decode_cpp
Rcpp::CharacterVector puny_decode_cpp(Rcpp::CharacterVector domains, bool strict);
RcppExport SEXP _punycoder_puny_decode_cpp(SEXP domainsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type domains(domainsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(puny_decode_cpp(domains, strict));
    return rcpp_result_gen;
END_RCPP
}
// url_encode_cpp
Rcpp::CharacterVector url_encode_cpp(Rcpp::CharacterVector urls, bool strict);
RcppExport SEXP _punycoder_url_encode_cpp(SEXP urlsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(url_encode_cpp(urls, strict));
    return rcpp_result_gen;
END_RCPP
}
// url_decode_cpp
Rcpp::CharacterVector url_decode_cpp(Rcpp::CharacterVector urls, bool strict);
RcppExport SEXP _punycoder_url_decode_cpp(SEXP urlsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(url_decode_cpp(urls, strict));
    return rcpp_result_gen;
END_RCPP
}
// parse_url_cpp
Rcpp::List parse_url_cpp(Rcpp::CharacterVector urls, bool encode_domains);
RcppExport SEXP _punycoder_parse_url_cpp(SEXP urlsSEXP, SEXP encode_domainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< bool >::type encode_domains(encode_domainsSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_url_cpp(urls, encode_domains));
    return rcpp_result_gen;
END_RCPP
}
// validate_domain_cpp
Rcpp::List validate_domain_cpp(Rcpp::CharacterVector domains, bool strict);
RcppExport SEXP _punycoder_validate_domain_cpp(SEXP domainsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type domains(domainsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_domain_cpp(domains, strict));
    return rcpp_result_gen;
END_RCPP
}
// backend_info_cpp
Rcpp::List backend_info_cpp();
RcppExport SEXP _punycoder_backend_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(backend_info_cpp());
    return rcpp_result_gen;
END_RCPP
}
// compare_backends_cpp
Rcpp::List compare_backends_cpp(Rcpp::CharacterVector input, std::string mode, bool strict);
RcppExport SEXP _punycoder_compare_backends_cpp(SEXP inputSEXP, SEXP modeSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_backends_cpp(input, mode, strict));
    return rcpp_result_gen;
END_RCPP
}
